config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :properties
  resources :contractors
  resources :realtors
  resources :homes

  root to: "homes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :properties
  has_many :realtors, through: :properties
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :contractor
  belongs_to :realtor

  validates :vacancy, inclusion: { in: [true, false] }
end

app/models/realtor.rb
class Realtor < ApplicationRecord
  has_many :properties
  has_many :contractors, through: :properties
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  def index
    @contractors = Contractor.all
  end

  def show
    @contractor = Contractor.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to @property
    else 
      render :new, flash: { error: "sorry try creating again" }
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to @property
    else
      render :edit
    end
  end
  
  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    redirect_to properties_path
  end
  
  private

  def property_params
    params.require(:property).permit(:address, :vacancy, :lawn_care, :plumbing, :electrical, :realtor_id, :contractor_id)
  end
end

app/controllers/realtors_controller.rb
class RealtorsController < ApplicationController
  def index
    @realtors = Realtor.all
  end

  def show
    @realtor = Realtor.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/views/contractors/index.html.erb
<div class="text-center px-5 mx-5"> 

<h1 style="color: white"> List of All Available Contractors </h1>

<ul style="list-style-type: none;">
  <% @contractors.each do |contractor|%>
    <li>
      <%= link_to contractor.name, contractor_path(contractor)%>
    </li>
  <% end %>
</ul>

</div>

app/views/contractors/show.html.erb
<div class="text-center px-5 mx-5">  

<h1 style="color: white"><%= @contractor.name%></h1>

<br>

<h2 style="color: white"> Contractor Field Specialty </h2>

<br>


<h3 style="color: white">Lawn Care: <%= @contractor.lawn_care %></h3>

<br>

<h3 style="color: white">Plumbing Work: <%= @contractor.plumbing %></h3>

<br>

<h3 style="color: white">Electrical Work: <%= @contractor.electrical %></h3>

<br>
<h2 style="color: white"> List of Properties Currently Managed: </h2>

<ul style="list-style-type: none;">
<% @contractor.properties.each do |property|%>
  <li>
  <%= link_to property.address, property_path(property)%>
  </li>
  <% end %>
</ul>

</div>

app/views/homes/index.html.erb
<div class="container">
<%# <div class="d-flex flex-column justify-content-center"> %>
<h1 class="text-center" style="color: white"> Welcome to the PCA Property Management landing page </h1>

<br>

  <h2 class="text-center" style="color: white"> Who we are </h2>
    <p class="text-center px-5 mx-5" style="color: white"> 
      Here at PCA Property Management, we aim to provide a network for realty teams 
      to manage vacant properties. Currently we have a system in place where upon intitial inspection
      the realty team can write assessments of the properties condition. From there the realty team
      can assign jobs to our trusted team of licensed contractors. Take a look through our site to 
      find out more.
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Propertymanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render "shared/navbar" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/properties/edit.html.erb
<%= form_for @property do |form| %>
  <%= form.label 'Property Address' %><br>
  <%= form.text_field :address %><br>

  <%= form.label 'Vacancy' %><br>
  Yes<%= form.radio_button :vacancy, true%>
  No<%= form.radio_button :vacancy, false%><br>

  <%= form.label 'Lawn Care' %><br>
  <%= form.text_area :lawn_care %><br>

  <%= form.label 'Plumbing' %><br>
  <%= form.text_area :plumbing %><br>

  <%= form.label 'Electrical' %><br>
  <%= form.text_area :electrical %><br>

  <%= form.submit "Submit Update" %>
<% end %>

app/views/properties/index.html.erb
<div class="text-center px-5 mx-5"> 

<h1 style="color: white"> List of All Manageable Properties </h1>

<ul style="list-style-type: none;">
  <% @properties.each do |property|%>
    <li>
      <%= link_to property.address, property_path(property)%>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new property", new_property_path, class:"buttonz" %> 

</div>

app/views/properties/new.html.erb
<main>
<h1 class="text-center">New Property Form</h1>

<br>

<%= form_for(@property) do |form|%>

<div class="text-center">
<h6> Please Enter Property Address: </h6>
  <%= form.text_area :address%>
</div>

<br>

<div class="text-center">
<h6> Is the Property Vacant? </h6> 
<table class="radio-values"> 
  <tr> 
    <td><%= form.label :vacancy, "Yes", value: true%></td>
    <td><%= form.radio_button :vacancy, true%></td>

     <td><%= form.label :vacancy, "No", value: false%></td>
    <td><%= form.radio_button :vacancy, false%></td>
  </tr>
</table>
</div>  

<br>

<div class="text-center">
<h3>Please assign this property to a realty team </h3>
<%= form.collection_select :realtor_id, Realtor.all, :id, :name%>
</div>

<br>

<div class="text-center">
<h3>Please assign this property to a contractor team </h3>
<%= form.collection_select :contractor_id, Contractor.all, :id, :name%>
</div>

<br>
<br>

<div class="text-center">
<h3> Post inspection work list:</h3>
</div>

<div class="text-center">
<h6> Work order for the lawn: </h6>
<%= form.text_area :lawn_care%>
</div>

<br>

<div class="text-center">
<h6> Work order for the plumbing: </h6>
<%= form.text_area :plumbing%>
</div>

<br>

<div class="text-center">
<h6> Work order for the electrical: </h6>
<%= form.text_area :electrical%>
</div>
<br>

<div class="text-center">
<%= form.submit class:"buttonz"%>
</div>

</main>
<% end %>

app/views/properties/show.html.erb
<div class="text-center px-5 mx-5">

<h1 style="color: white">Property Address: <%= @property.address%></h1>

<br>

<h3 style="color: white"> Vacancy: <%= @property.vacancy%> </h3>

<br>

<h3 style="color: white"> Realty Team Managing Property: </h3>

  <%= link_to @property.realtor.name, realtor_path(@property.realtor)%>

<br>

<h3 style="color: white"> Contractor Team Maintaining Property: </h3>

  <%= link_to @property.contractor.name, contractor_path(@property.contractor)%>

<br>

<h2 style="color: white"> Work Description:</h2>

<br>

<h3 style="color: white">Lawn Care: <%= @property.lawn_care %></h3>

<br>

<h3 style="color: white">Plumbing Work: <%= @property.plumbing %></h3>

<br>

<h3 style="color: white">Electrical Work: <%= @property.electrical %></h3>

<br>

<label style="color: white"> Update this property </label>
 <%= button_to "Update", edit_property_path(@property), method: :get%>

<br>

<label style="color: white"> Delete this property </label>
 <%= button_to "Delete", @property, method: "delete"%>
 
 </div>

app/views/realtors/index.html.erb
<div class="text-center px-5 mx-5">  
<h1 style="color: white"> List of Available Realtors:</h1>

 <ul style="list-style-type: none;">
    <% @realtors.each do |realtor|%>
      <li>
        <%= link_to realtor.name, realtor_path(realtor)%>
      </li>
    <% end %>
  </ul>
</div>

app/views/realtors/show.html.erb
<div class="text-center px-5 mx-5">  

<h1 style="color: white"><%= @realtor.name%></h1>

<br>

<h2 style="color: white">List of Properties Currently Managed: </h2>

 <ul style="list-style-type: none;">
  <% @realtor.properties.each do |property|%>
    <li>
      <%= link_to property.address, property_path(property)%>
      <% end %>
    </li>
</ul>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">PCA Property Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
       <li class="nav-item">
       <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
       <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>

      <li class="nav-item">
        <a class="nav-link" href="/homes">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/realtors">Realtors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contractors">Contractors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/properties">Properties</a>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<%# unused %>